2021-11-28 01:23:54,830 ERROR: Exception on /api/profile [POST] [in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2746, in _determine_joins
    self.primaryjoin = join_condition(
  File "<string>", line 2, in join_condition
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 1229, in _join_condition
    raise exc.NoForeignKeysError(
sqlalchemy.exc.NoForeignKeysError: Can't find any foreign key relationships between 'profile' and 'profile_arrondissement'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/controllers/account_controllers.py", line 29, in create_profile
    response = create_profile_followed_arr(data)
  File "/Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/services/profile_service.py", line 22, in create_profile_followed_arr
    profile, status = get_profile_by_email(email)
  File "/Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/services/profile_service.py", line 12, in get_profile_by_email
    profile = find_profile_by_email(email)
  File "/Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/repositories/profile_repo.py", line 7, in find_profile_by_email
    profile = Profile.query.filter_by(email=email) \
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3380, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3419, in _do_configure_registries
    mapper._post_configure_properties()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1890, in _post_configure_properties
    prop.init()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/interfaces.py", line 222, in init
    self.do_init()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2144, in do_init
    self._setup_join_conditions()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2240, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2635, in __init__
    self._determine_joins()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2768, in _determine_joins
    util.raise_(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship Profile.followed_arr - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
2021-11-28 01:24:41,399 ERROR: Exception on /api/profile [POST] [in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/controllers/account_controllers.py", line 29, in create_profile
    response = create_profile_followed_arr(data)
  File "/Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/services/profile_service.py", line 22, in create_profile_followed_arr
    profile, status = get_profile_by_email(email)
  File "/Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/services/profile_service.py", line 12, in get_profile_by_email
    profile = find_profile_by_email(email)
  File "/Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/repositories/profile_repo.py", line 7, in find_profile_by_email
    profile = Profile.query.filter_by(email=email) \
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3380, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3415, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class Profile->profile'. Original exception was: Could not determine join condition between parent/child tables on relationship Profile.followed_arr - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
2021-11-28 01:24:50,813 INFO: data swarm start [in /Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/__init__.py:102]
2021-11-28 01:26:18,846 INFO: data swarm start [in /Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/__init__.py:102]
2021-11-28 10:17:15,072 INFO: data swarm start [in /Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/__init__.py:102]
2021-11-28 11:10:04,583 INFO: data swarm start [in /Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/__init__.py:102]
2021-11-28 18:30:15,329 INFO: data swarm start [in /Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/__init__.py:102]
2021-11-28 22:28:19,435 INFO: data swarm start [in /Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/__init__.py:102]
2021-11-28 23:10:09,322 INFO: data swarm start [in /Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/__init__.py:102]
2021-11-28 23:15:09,505 INFO: Starting patinoire scheduler [in /Users/mokhtarsafir/Projects/Tp2.web.avance/worker.py:20]
2021-11-28 23:26:04,820 INFO: data swarm start [in /Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/__init__.py:102]
2021-12-01 11:32:15,001 INFO: data swarm start [in /Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/__init__.py:105]
2021-12-02 14:35:26,638 INFO: data swarm start [in /Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/__init__.py:105]
2021-12-02 14:37:30,957 INFO: data swarm start [in /Users/mokhtarsafir/Projects/Tp2.web.avance/inf5190_projet_src/__init__.py:105]
